### ISSUE TITLE
Error reading BMP file header

### ISSUE THREAD

**Issue by mrx23dot** [autotrace/autotrace#48]
Attached valid bmp (generated with imagemagick) fails.

autotrace\autotrace.exe -input-format BMP lego_5.bmp
Error reading BMP file header
[lego_5.zip](https://github.com/autotrace/autotrace/files/7453622/lego_5.zip)

AutoTrace version 0.40.0.

**Comment by WillNilges** [comment]
Getting the same issue.

```
Thread 1 "xournalpp" received signal SIGFPE, Arithmetic exception.
0x00007f0ce031058f in compute_color_rgb (icolor=<optimized out>, boxp=<optimized out>,
    histogram=0x7f0cc68a2010, quantobj=<optimized out>) at src/median.c:349
```

Fuller stacktrace
```gdb
#0  0x00007f0ce031058f in compute_color_rgb
    (icolor=<optimized out>, boxp=<optimized out>, histogram=0x7f0cc68a2010, quantobj=<optimized out>) at src/median.c:349
#1  select_colors_rgb (quantobj=<optimized out>, histogram=0x7f0cc68a2010)
    at src/median.c:381
#2  0x00007f0ce0310af6 in median_cut_pass1_rgb
    (ignoreColor=0x564956172dd0, image=0x5649561861d0, quantobj=0x56495624d440)
    at src/median.c:720
#3  quantize
    (image=0x5649561861d0, ncolors=<optimized out>, bgColor=0x564956172dd0, iQuant=0x7fff8ea648e8, exp=<optimized out>) at src/median.c:844
#4  0x00007f0ce030a6c4 in at_splines_new_full
    (bitmap=0x5649561861d0, opts=0x56495618d360, msg_func=<optimized out>, msg_data=<optimized out>, notify_progress=notify_progress@entry=0x0, progress_data=progress_data@entry=0x0, test_cancel=0x0, testcancel_data=0x0) at src/autotrace.c:262
#5  0x00007f0ce030a7d3 in at_splines_new
    (bitmap=<optimized out>, opts=<optimized out>, msg_func=<optimized out>, msg_data=<optimized out>) at src/autotrace.c:228
#6  0x00007f0ce18893a0 in transcribe_image (L=0x564955b29808) at src/lua_util.c:40
```
